export const products = [
  // SHOES
  {
    name: "New balance 530",
    price: 999,
    description: "Classic New Balance 530 shoe",
    imagePrefix: "Newbalance530Img",
    video: "",
    category: "shoes",
  },
  {
    name: "Samba OG",
    price: 999,
    description: "Adidas Samba OG sneaker",
    imagePrefix: "SambaOGimg",
    video: "",
    category: "shoes",
  },
  {
    name: "New balance 9060",
    price: 999,
    description: "New Balance 9060 shoe",
    imagePrefix: "new_balance_9060_img",
    video: "",
    category: "shoes",
  },
  {
    name: "Air Jordan 5 RETRO Wolf Grey 2026",
    price: 999,
    description: "Air Jordan 5 RETRO Wolf Grey 2026",
    imagePrefix: "air_jordan_retro_img",
    video: "",
    category: "shoes",
  },
  {
    name: "Nike Wmns P-6000 gold",
    price: 999,
    description: "Nike Wmns P-6000 gold",
    imagePrefix: "nike_p600_img",
    video: "",
    category: "shoes",
  },
  {
    name: "Nike Mind 001 Slide Solar Red",
    price: 999,
    description: "Nike Mind 001 Slide Solar Red",
    imagePrefix: "nike_slide_img",
    video: "",
    category: "shoes",
  },

  // CLOTHES
  {
    name: "LAZY EYE LINEN SHIRT IN BROWN",
    price: 999,
    description: "LAZY EYE LINEN SHIRT IN BROWN",
    imagePrefix: "LAZYEYELINENSHIRTINBROWN",
    video: "",
    category: "clothes",
  },
  {
    name: "DANCING MAN SHACKET IN BLUE",
    price: 999,
    description: "DANCING MAN SHACKET IN BLUE",
    imagePrefix: "dancingmanimg",
    video: "",
    category: "clothes",
  },
  {
    name: "BADLY LOGO PANTS ONE OF ONE",
    price: 999,
    description: "BADLY LOGO PANTS ONE OF ONE",
    imagePrefix: "BLEACHEDPOCKETPANT",
    video: "",
    category: "clothes",
  },
  {
    name: "TIGER FULL SLEEVE T-SHIRT [UNISEX]",
    price: 999,
    description: "TIGER FULL SLEEVE T-SHIRT [UNISEX]",
    imagePrefix: "tiger_full_sleeve",
    video: "",
    category: "clothes",
  },
  {
    name: "TWIRL TOP IN PINK",
    price: 999,
    description: "TWIRL TOP IN PINK",
    imagePrefix: "PINKTWIRLTOP",
    video: "",
    category: "clothes",
  },
  {
    name: "SAFARI SHORTS",
    price: 999,
    description: "SAFARI SHORTS",
    imagePrefix: "eyespy",
    video: "",
    category: "clothes",
  },
  {
    name: "PATCH WORK PANT",
    price: 999,
    description: "PATCH WORK PANT",
    imagePrefix: "PATCHWORKPANTS",
    video: "",
    category: "clothes",
  },
  {
    name: "TIGER TOTE BAG",
    price: 999,
    description: "TIGER TOTE BAG",
    imagePrefix: "TIGER_TOTE_BAG",
    video: "",
    category: "clothes",
  },
  {
    name: "RICH HOODIE IN OYSTER GREY [UNISEX]",
    price: 999,
    description: "RICH HOODIE IN OYSTER GREY [UNISEX]",
    imagePrefix: "jw_hoodie",
    video: "",
    category: "clothes",
  },
  {
    name: "RICH POLO FULL SLEEVE IN MAROON [UNISEX]",
    price: 999,
    description: "RICH POLO FULL SLEEVE IN MAROON [UNISEX]",
    imagePrefix: "RICHPOLOFULLSLEEVE",
    video: "",
    category: "clothes",
  },
  {
    name: "PHASE JACKET IN YELLOW",
    price: 999,
    description: "PHASE JACKET IN YELLOW",
    imagePrefix: "yellow_jacket",
    video: "",
    category: "clothes",
  },
  {
    name: "HEAVY PLEATED PANTS IN BLACK [UNISEX]",
    price: 999,
    description: "HEAVY PLEATED PANTS IN BLACK [UNISEX]",
    imagePrefix: "black_pant",
    video: "",
    category: "clothes",
  },

  // MIDDLE
  {
    name: "Bluorang Cap",
    price: 999,
    description: "Bluorang Cap",
    imagePrefix: "bluorangcapimg",
    video: "",
    category: "middle",
  },
  {
    name: "Bluorang Banner",
    price: 999,
    description: "Bluorang Banner",
    imagePrefix: "bluornngImg",
    video: "",
    category: "middle",
  },
  {
    name: "Bluorang Grp",
    price: 999,
    description: "Bluorang Grp",
    imagePrefix: "bluoranggroupimg",
    video: "",
    category: "middle",
  },
  {
    name: "Bluorang Car",
    price: 999,
    description: "Bluorang car",
    imagePrefix: "bluorangcarimg",
    video: "",
    category: "middle",
  },

  // CAP
  {
    name: "Blue Orange Cap",
    price: 100,
    description: "Structured cap with blue and orange panel detailing.",
    imagePrefix: "middlecap1img",
    video: "",
    category: "cap",
  },
  {
    name: "Blue Orange Cap 2",
    price: 999,
    description: "Add a warm, earthy accent to your streetwear looks with the Rust and Beige Cap. This rust six panel cap is crafted from 100% twill cotton, offering a lightweight yet structured fit for all-day comfort. The premium puff embroidered rust & beige cap design with a branded wordmark delivers subtle contrast and a refined finish.",
    imagePrefix: "middlecap2img",
    video: "",
    category: "cap",
  },
];